version: "2"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - db:mysql
        ports:
            - 8080:80
            - 18081:10081
        volumes:
            - ./src/:/var/www/html
        environment:
            ZS_ADMIN_PASSWORD: admin
            # ZS_PRODUCTION: "true"
        container_name: "web_app"
        # command: sh /srv/scripts/post-up.sh

    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: example
